### ISSUE TITLE
All posts are dated 2021-02-24

### ISSUE THREAD

**Issue by JamieKitson** [kaihendry/geekout.org.uk#4] opened 2021-03-22 09:42 UTC
All posts are dated 2021-02-24.

![image](https://user-images.githubusercontent.com/1188974/111970078-ce223880-8af2-11eb-9b95-f3f996152794.png)

I'm assuming this is screwing up the order the posts are displayed/navigated in too.

**Comment by JamieKitson** [comment] 2021-03-22 09:47
https://stackoverflow.com/a/36243002/139560

**Comment by JamieKitson** [comment] 2021-05-10 09:49
`git log --pretty=%at --name-status --reverse | perl -ane '($x,$f)=@F;next if !$x;$t=$x,next if !defined($f)||$s{$f};$s{$f}=utime($t,$t,$f),next if $x=~/[AM]/;'`

https://github.com/JamieKitson/geekout.org.uk/commit/c0610e562e1f89868c0f55390702c92aa00c2a91

**Comment by JamieKitson** [comment] 2021-05-10 10:58
Solution is to use --gettime to force ikiwiki to get time stamps from git and --rebuild to rebuild the entire wiki.

https://ikiwiki.info/forum/Blog_posting_times_and_ikiwiki_state/
https://ikiwiki.info/bugs/IkiWiki_does_not_use_file__39__s_mtime_for_Last_Edited/

**Comment by kaihendry** [comment] 2021-05-10 11:18
I'm doing that here I think: https://github.com/kaihendry/geekout.org.uk/blob/master/bin/build-site

This gets employed from the Action https://github.com/kaihendry/geekout.org.uk/actions/workflows/ci.yaml

**Comment by kaihendry** [comment] 2021-06-16 20:39
I can confirm this issue if fixed in https://github.com/kaihendry/geekout.org.uk/issues/5#issuecomment-862706079

**Comment by kaihendry** [comment] 2021-06-17 10:07
Hmmm, dates appear to be wrong still upon https://geekout.org.uk/ ... any idea @JamieKitson ?

I'm really confused since when I do the build locally myself, e.g.

1. `docker build -t geekout .`
2. `docker run --rm -v /tmp/out:/home/jamie/geekout.org.uk/out geekout`
3. /tmp/out has the right dates!

**Comment by JamieKitson** [comment] 2021-06-17 16:09
You have to `--gettime --rebuild` for each build.

https://github.com/JamieKitson/geekout.org.uk/commit/2646e65678922f55c6c3ccda64c68bc9286c9bc0

**Comment by kaihendry** [comment] 2021-06-17 16:37
That's exactly what the CI is running https://github.com/kaihendry/geekout.org.uk/blob/master/build.sh#L11

**Comment by kaihendry** [comment] 2021-06-17 16:47
The only thing I notice that's different with the docker run is

![image](https://user-images.githubusercontent.com/765871/122439646-bf351000-cf93-11eb-95b8-e069bed7aa10.png)

When I run it locally I see:


    error: cannot pull with rebase: Your index contains uncommitted changes.
    error: please commit or stash them.
    'git pull --prune origin' failed:  at /usr/share/perl5/IkiWiki/Plugin/git.pm line 251.

**Closed as completed** 2021-07-03 08:50 UTC
